server:
  port: 8080
  servlet:
    context-path: /invoice-service

spring:
  application:
    name: invoice-service
  datasource:
    url: jdbc:h2:file:~/invoice-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: admin
    password: 12345678
  h2:
    console:
      enabled: true
      path: /invoice-service/h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop # update
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          import_files: data/initial-data.sql
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true



